pywren:
    storage_bucket: '<BUCKET>'
    #storage_prefix: pywren.jobs
    #storage_backend: ibm_cos
    #compute_backend: ibm_cf
    #rabbitmq_monitor: <True/False>
    #data_cleaner: <True/False>
    #runtime :
    runtime_timeout: 15000     # Default timeout
    #runtime_memory: 256         # Default memory
    #invocation_retry: <True/False>
    #retry_sleeps: [1, 5, 10, 20, 30]
    #retries: 5

ibm:
    iam_api_key: 'GZ8BPKZhq2apPE0iQVSt4Rv80mQYatvTAi7p02TG-unr'

ibm_cf:
    endpoint    : '<FUNCTIONS_ENDPOINT>'
    namespace   : '<NAMESPACE>'
    namespace_id : '<NAMESPACES_ID>'

ibm_cos:
    bucket      : '<BUCKET>'
    endpoint    : '<ENDPOINT>'
    private_endpoint: '<PRIVATE_ENDPOINT>'
    api_key     : '<API_KEY>'
    access_key : '<ACCESS_KEY>'
    secret_key : '<SECRET_KEY>'

#rabbitmq:
    #amqp_url   : <RABBIT_AMQP_URL>  # amqp://

#knative:
#   endpoint    : <ISTIO_INGRESS_ENDPOINT>
#   docker_user : <DOCKER_HUB_USERNAME>
#   docker_token: <DOCKER_HUB_TOKEN>

#swift:
    #auth_url   : <SWIFT_AUTH_URL>
    #region     : <SWIFT_REGION>
    #user_id    : <SWIFT_USER_ID>
    #project_id : <SWIFT_PROJECT_ID>
    #password   : <SWIFT_PASSWORD>