lithops: 
    storage_bucket: <BUCKET_NAME>
    #storage_backend: ibm_cos
    #compute_backend: ibm_cf
    #rabbitmq_monitor: <True/False>
    #remote_invoker: <True/False>
    #data_cleaner: <True/False>
    #runtime : <RUNTIME_NAME>
    #runtime_timeout: 600
    #runtime_memory: 256
    #workers: <MAX_NUM_OF_WORKERS>
    #data_limit: 4  # in MiB

#ibm:
   #iam_api_key: <IAM KEY>

ibm_cf:
    endpoint    : <REGION_ENDPOINT>
    namespace   : <NAMESPACE>
    api_key     : <API_KEY>
    #namespace_id : <NAMESPACE_ID> # Only for IAM auth

ibm_cos:
    endpoint    : <REGION_ENDPOINT>
    private_endpoint: <PRIVATE_REGION_ENDPOINT>
    api_key     : <API_KEY>
    #access_key : <ACCESS_KEY>  # Optional
    #secret_key : <SECRET_KEY>  # Optional